;;;; pgn-abnf.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'pgn-abnf
      'pgn-abnf
      (scheme#list)
      '((pgn-db . pgn-abnf#pgn-db)
        (pgn-game . pgn-abnf#pgn-game)
        (pgn-tag . pgn-abnf#pgn-tag)
        (pgn-move . pgn-abnf#pgn-move)
        (pgn-tag-list . pgn-abnf#pgn-tag-list)
        (pgn-move-list . pgn-abnf#pgn-move-list)
        (pgn-all-moves-with-result . pgn-abnf#pgn-all-moves-with-result))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
