;;;; pgn-abnf.import.scm - GENERATED BY CHICKEN 5.3.0 -*- Scheme -*-

(##sys#with-environment
  (lambda ()
    (##sys#register-compiled-module
      'pgn-abnf
      'pgn-abnf
      (scheme#list)
      '((pgn-db . pgn-abnf#pgn-db) (pgn-game . pgn-abnf#pgn-game))
      (scheme#list)
      (scheme#list))))

;; END OF FILE
